pipeline {
    agent any

    stages {
        stage('Git') {
            steps {
                sh 'cd ~/project/'
                git branch: 'main', url: 'https://github.com/ANGorbachev/MLOps_1.git'
            }
        }
        stage('Environment preparation') {
            steps {
                sh 'cd ./lab2'
                echo "Installing Dependencies (begin)"
                sh 'pip install -r requirements.txt'
                echo "Installing Dependencies (end)"
            }
        }
        stage('Data Creation') {
            steps {
                echo "Create Dataset (begin)"
                sh 'python create_dataset.py'
                echo "Create Dataset (end)"
            }
        }
        stage('Data Preprocessing') {
            steps {
                echo "Data Preprocessing (begin)"
                sh 'python data_preprocessing.py'
                echo "Data Preprocessing (end)"
            }
        }
        stage('Train Model') {
            steps {
                echo "Training model (begin)"
                sh 'python model_training.py'
                echo "Training model (end)"
            }
        }
        stage('Test Model') {
            steps {
                echo "Testing model (begin)"
                sh 'python model_testing.py'
                echo "Testing model (end)"
            }
        }

    }
}