version: '3.7'

services:
    streamlit-app:
        build: ./
        command: streamlit run translator.py --server.port=8501 --server.address=0.0.0.0
        volumes:
            - ./:/app
        ports:
            - 8501:8501
        restart: always
